name: Demo
run-name: ${{github.actor}} is testing the Demo workflow
on: [push]
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job 1"
  Job2:
    runs-on: ubuntu-latest
    needs: Job1
    steps:
      - run: echo "this is job 2"
      
